### ISSUE TITLE
 How to properly authenticate to Cloudflare?

### ISSUE THREAD

**Issue by matt-j-so** [cloudflare/helm-charts#35]
I'm trying to use the `cloudflare-tunnel` helm chart, but I'm not sure how to configure the below options properly:

```
cloudflare:
  # Your Cloudflare account number.
  account: ""
  # The secret for the tunnel.
  secret: ""
```

Could you provide instructions on how to get Cloudflare account number and secret for the tunnel ?
I can't find any documentation or example on how to use it properly.

Thanks in advance for any help :)
