### ISSUE TITLE
Ingress hostnames aren't propagated automatically

### ISSUE THREAD

**Issue by bhvk0** [cloudflare/helm-charts#41]
Ingress hostnames aren't propagated automatically. In the example below you can see our configuration:

```
cloudflare:
  ingress:
    # The first rule proxies traffic to the httpbin sample service named web-server at port 80
    - hostname: prom-server.domain.com
      service: https://prometheus-server.monitoring:80
```

But these settings aren't applying automatically. It means that I still have to add public hostnames in Tunnel configuration manually. Are there any additional settings required?

![Screenshot 2023-07-05 at 18 16 40](https://github.com/cloudflare/helm-charts/assets/108488374/9974c475-67c2-4258-bc51-d4a3310adad6)
