### ISSUE TITLE
Upgrade cloudflared version

### ISSUE THREAD

**Issue by pvickery-ParamountCommerce** [cloudflare/helm-charts#79]
The current cloudflared version is over a year out of date and needs to be updated to a modern version.

Related to https://github.com/cloudflare/helm-charts/pull/37/files

**Comment by MrFrydae** [comment]
You can override the version tag inside your `values.yaml` file in the following section:

```yaml
image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  # If supplied, this overrides "appVersion"
  tag: "2024.9.1" # <----- Change this
  ```
