### ISSUE TITLE
Feature Request: Support existing secret for remote tunnel

### ISSUE THREAD

**Issue by MirTalpur** [cloudflare/helm-charts#97]
# Description

Currently we have to following values we can pass into the `cloudflare-tunnel-remote` helm chart for the tunnel token
```
# Cloudflare parameters.
cloudflare:
  tunnel_token: ""
```

This creates a secret in the k8s cluster that is referenced by the deployment. I want to be able to utilize an existing secret that already exists on the cluster as usually my infra code gets deployed with IaC. 

This pattern is utilized by some of the popular helm charts as well such as `postgres`, `artifactory-oss`, `harbor`, etc.

I'd be happy to help out by creating a PR for this feature, if needed as well.

**Comment by 0x4272616E646F6E** [comment]
@MirTalpur This repo doesn't seem to be maintained unfortunately.
I was trying to accomplish the same thing earlier today.
If you're using Flux & Kustomize, I found just layering the secret like this allowed me to use the existing secret.

```yaml
# kustomize.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: cloudflared
  valuesFrom:
  - kind: ConfigMap
    name: cloudflared-config-map
    valuesKey: values.yaml
  - kind: Secret
    name: cloudflared-secrets
    valuesKey: values.yaml
````

```yaml
# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config-map
  namespace: cloudflared
data:
  values.yaml: |-
    # Default values for cloudflare-tunnel.

    # Cloudflare parameters.
    # cloudflare:
    #   tunnel_token: ""

other remaining values...
```

```yaml
# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secrets
  namespace: cloudflared
type: Opaque
stringData:
  values.yaml: |
    cloudflare:
      tunnel_token: ""
```
